# Generated by Django 4.0.4 on 2023-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sector_alter_postulacioninstr_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de solicitud')),
                ('rutSolcitante', models.CharField(max_length=50, verbose_name='Rut de soliitante')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de soliitante')),
                ('detalle', models.CharField(max_length=50, verbose_name='Detalle solicitud')),
                ('proyecto', models.CharField(max_length=50, verbose_name='Proyecto')),
                ('jefatura', models.CharField(max_length=50, verbose_name='jefatura')),
                ('fecha', models.CharField(max_length=50, verbose_name='fecha')),
            ],
        ),
    ]
